let arr=[]
arr.push("aya")
arr.push("elbaz")
arr.push(20)
arr.push(true)
arr.push(false)
arr.push(null)
arr.push(undefined)
arr.push(NaN)
arr.push(Infinity)
arr.push(-Infinity)
console.log(arr)
arr.pop()
console.log(arr)
arr.shift()
console.log(arr)
arr.unshift("aya")
console.log(arr)
arr.splice(1,2)
console.log(arr)
arr.slice(1,3)
console.log(arr)
arr.join(" ")
console.log(arr)